language: cpp
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.48-dev libyajl-dev libxml2-dev libxqilla-dev
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - pushd ${HOME}
 - wget http://www.openframeworks.cc/versions/v0.8.1/of_v0.8.1_linux64_release.tar.gz -O /tmp/of_v0.8.1_linux64_release.tar.gz
 - tar xvfz /tmp/of_v0.8.1_linux64_release.tar.gz
 - mv of_v0.8.1_linux64_release/ openframeworks
 - popd
 - ./download_addons.sh
 - sudo ${HOME}/openframeworks/script/linux/ubuntu/install_dependencies.sh
 - sudo ${HOME}/openframeworks/script/linux/ubuntu/install_codecs.sh
script: make Release
branches:
  only:
    - master
notifications:
  email:
    - dev@groolot.net
  irc:
    channels:
      - "chat.freenode.net#vilain"
cache: apt
