language: cpp
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.48-dev libyajl-dev libxml2-dev libxqilla-dev
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - pushd ${HOME}
 - wget http://www.openframeworks.cc/versions/v0.8.1/of_v0.8.1_linux64_release.tar.gz -O /tmp/of_v0.8.1_linux64_release.tar.gz
 - tar xvfz /tmp/of_v0.8.1_linux64_release.tar.gz
 - mv of_v0.8.1_linux64_release/ openframeworks
 - pushd openframeworks/addons
 - git clone https://github.com/groolot/ofxAnimatable.git
 - git clone https://github.com/groolot/ofxAppUtils.git
 - git clone https://github.com/groolot/ofxAutoControlPanel.git
 - git clone https://github.com/groolot/ofxBlur.git
 - git clone https://github.com/groolot/ofxControlPanel.git
 - git clone https://github.com/groolot/ofxCv.git
 - git clone https://github.com/groolot/ofxCvOpticalFlowLK.git
 - git clone https://github.com/groolot/ofxDirList.git
 - git clone https://github.com/groolot/ofxDmx.git
 - git clone https://github.com/groolot/ofxDraggable.git
 - git clone https://github.com/groolot/ofxFenster.git
 - git clone https://github.com/groolot/ofxFTGL.git
 - git clone https://github.com/groolot/ofxFX.git
 - git clone https://github.com/groolot/ofxImageSequence.git
 - git clone https://github.com/groolot/ofxMSAInteractiveObject.git
 - git clone https://github.com/groolot/ofxMSATimer.git
 - git clone https://github.com/groolot/ofxMtlMapping2D.git
 - git clone https://github.com/groolot/ofxNamedVariables.git
 - git clone https://github.com/groolot/ofxOscRouter.git
 - git clone https://github.com/groolot/ofxPlaylist.git
 - git clone https://github.com/groolot/ofxPostProcessing.git
 - git clone https://github.com/groolot/ofxProjectorBlend.git
 - git clone https://github.com/groolot/ofxRange.git
 - git clone https://github.com/groolot/ofxRenderManager.git
 - git clone https://github.com/groolot/ofxTextInputField.git
 - git clone https://github.com/groolot/ofxTextureServer.git
 - git clone https://github.com/groolot/ofxTimecode.git
 - git clone https://github.com/groolot/ofxTimeline.git
 - git clone https://github.com/groolot/ofxTweakbar.git
 - git clone https://github.com/groolot/ofxTween.git
 - git clone https://github.com/groolot/ofxUI.git
 - git clone https://github.com/groolot/ofxVideoMapping.git
 - git clone https://github.com/groolot/ofxWordPalette.git
 - popd
 - popd
 - sudo apt-get install freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile-dev libfreeimage-dev libcairo2-dev libgtk2.0-dev python-lxml python-argparse libfreetype6-dev portaudio19-dev libssl-dev libpulse-dev
 - sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev gstreamer0.10-ffmpeg gstreamer0.10-pulseaudio gstreamer0.10-x gstreamer0.10-plugins-bad gstreamer0.10-alsa gstreamer0.10-plugins-base gstreamer0.10-plugins-good
 - sudo apt-get install libmpg123-dev gstreamer0.10-plugins-ugly
script: make Release
branches:
  only:
    - master
notifications:
  email:
    - dev@groolot.net
  irc:
    channels:
      - "chat.freenode.net#vilain"
      - "chat.freenode.net#ammd"
      - "chat.freenode.net#bts-malraux"
cache: apt
