language: cpp
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8
 - ./install_prerequisites -f linux64 -i
script: PROJECT_CXX='g++-4.8' PROJECT_CC='gcc-4.8' make -e Release
branches:
  only:
    - master
notifications:
  email:
    - dev@groolot.net
  irc:
    channels:
      - "chat.freenode.net#vilain"
cache: apt
