language: cpp
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - ./install_prerequisites
script: make Release
branches:
  only:
    - master
notifications:
  email:
    - dev@groolot.net
  irc:
    channels:
      - "chat.freenode.net#vilain"
cache: apt
