language: cpp
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get install -qq g++-4.8
 - alias g++="g++-4.8"
 - ./install_prerequisites -f linux64 -i
script: make Release
branches:
  only:
    - master
notifications:
  email:
    - dev@groolot.net
  irc:
    channels:
      - "chat.freenode.net#vilain"
cache: apt
