language: cpp
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 0
 - ./install_prerequisites -f linux64 -i
 - echo "PROJECT_CXX=g++-4.8" >> config.make
 - echo "PROJECT_CC=gcc-4.8" >> config.make
script: make Release
branches:
  only:
    - master
notifications:
  email:
    - dev@groolot.net
  irc:
    channels:
      - "chat.freenode.net#vilain"
cache: apt
