#!/bin/bash

tput bold; echo -e "\n\tINFORMATION: your user must have 'sudo' power to install some requirements!\n\n"; tput sgr0

OF_DIRNAME=openframeworks

function usage {
    echo "Usage: $0 -f <linux|linux32|linux64|armRPI|armV6|armPANDA|armV7> -a" 1>&2;
    echo "" 1>&2;
    echo -e "\t-f flavour\tSets the flavour of your system to download the correct" 1>&2;
    echo -e "\t\t\tversion and install everything needed (openFrameworks+Addons) [optional]\n" 1>&2;
    echo -e "\t-a\t\tOnly download the openFrameworks Addons [optional]\n" 1>&2;
    exit 1;
}

function message {
    tput bold
    case $2 in
	warning)
	    tput setaf 3
	    ;;
	error)
	    tput setaf 1
	    ;;
	cool)
	    tput setaf 2
	    ;;
	*)
	    tput setaf 2
	    ;;
    esac
    echo -n -e $1
    tput sgr0
}

function failed_message {
    echo -e -n "\t["
    message "KO" error
    echo "]"
    exit 1
}

function successed_message {
    echo -e -n "\t["
    message "OK"
    echo "]"
}

function get_addons {
message "Install required ofxAddons"
INSTALL_DIR=${HOME}/${OF_DIRNAME}/addons
if [ -d ${INSTALL_DIR} ]
then
    VILAIN_DEPENDENCIES=($(cat addons.make))
    pushd ${INSTALL_DIR} >/dev/null
    for i in $(seq 0 $((${#VILAIN_DEPENDENCIES[@]} - 1)) )
    do
	if [ -d ${VILAIN_DEPENDENCIES[i]} ]
	then
	    pushd ${VILAIN_DEPENDENCIES[i]} >/dev/null
	    git pull >/dev/null 2>&1
	    popd >/dev/null
	else
	    git clone https://github.com/groolot/${VILAIN_DEPENDENCIES[i]}.git >/dev/null 2>&1
	fi
    done
    successed_message
    popd >/dev/null
    exit 0
else
    tput setaf 1;
    echo -e "\n\tNo AddOns have been installed due to absence of ${INSTALL_DIR}, required directory\n\tPlease re-run this script or file an issue on https://github.com/groolot/vilain/issues" >&2
    tput sgr0;
    exit 1
fi
}

while getopts ":f:d:a" options;
do
    case "${options}" in
        f)
	    f=${OPTARG}
	    if [ $f = "linux" ] || [ $f = "linux32" ];
	    then
		flavour="linux"
	    elif [ $f = "linux64" ];
	    then
		flavour="linux64"
	    elif [ $f = "armRPI" ] || [ $f = "armV6" ];
	    then
		flavour="linuxarmv6l"
	    elif [ $f = "armPANDA" ] || [ $f = "armV7" ];
	    then
		flavour="linuxarmv7l"
	    else
		usage
	    fi
	    ;;
	a)
	    get_addons
	    exit 0
	    ;;
        *)
	    usage
	    ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${flavour}" ];
then
    usage
fi

OF_VERSION=0.8.1
OF_FLAVOUR=${flavour}_release
OF_FILE=of_v${OF_VERSION}_${OF_FLAVOUR}.tar.gz

KERNEL_MAJOR_REQ=3
KERNEL_MINOR_REQ=6
GPP_MAJOR_REQ=4
GPP_MINOR_REQ=8
OS_REQ="GNU/Linux"

function verify_operating_system {
    message "${OS_REQ} operating system"
    if [ $(uname -o) != ${OS_REQ} ];
    then
	failed_message
    else
	successed_message
    fi
}

function verify_kernel_release {
    message "Linux kernel >= ${KERNEL_MAJOR_REQ}.${KERNEL_MINOR_REQ}"
    if [ $(uname -r | awk -F. '{printf("%d",$1)}') -ge ${KERNEL_MAJOR_REQ} ];
    then
	if [ $(uname -r | awk -F. '{printf("%d",$2)}') -ge ${KERNEL_MINOR_REQ} ];
	then
	    successed_message
	else
	    message ": please upgrade your kernel at least to ${KERNEL_MAJOR_REQ}.${KERNEL_MINOR_REQ}" error
	    failed_message
	fi
    else
	message ": please upgrade your kernel at least to ${KERNEL_MAJOR_REQ}.${KERNEL_MINOR_REQ}" error
	failed_message
    fi
}

function verify_gpp_available_version {
    message "GNU g++ >= ${GPP_MAJOR_REQ}.${GPP_MINOR_REQ} available"
    if [ $(which dpkg) ];
    then
	GPP_VERSION=$(dpkg -s g++ | grep Version | awk -F: '{print $3}')
    else
	message ": dpkg is not accessible to determine g++ availability" warning
	failed_message
    fi
    if [ $(echo $GPP_VERSION | awk -F. '{printf("%d",$1);}') -ge ${GPP_MAJOR_REQ} ];
    then
	if [ $(echo $GPP_VERSION | awk -F. '{printf("%d",$2);}') -ge ${GPP_MINOR_REQ} ];
	then
	    successed_message
	else
	    failed_message
	fi
    else
	failed_message
    fi
}

function verify_prerequisites {
    verify_operating_system
    verify_kernel_release
    verify_gpp_available_version
}

function get_toolchain {
    message "Install compilation toolchain + Git"
    sudo apt-get update -qq || failed_message
    sudo apt-get install -qq build-essential pkg-config g++ git || failed_message
    successed_message
}

function get_dep_libs {
    message "Install needed libraries (OF)"
    GSTREAMER_VERSION=0.10
    GSTREAMER_FFMPEG=gstreamer${GSTREAMER_VERSION}-ffmpeg
    apt-cache show libgstreamer1.0-dev >/dev/null
    exit_code=$?
    if [ $exit_code = 0 ]; then
	GSTREAMER_VERSION=1.0
	GSTREAMER_FFMPEG=gstreamer${GSTREAMER_VERSION}-libav
    fi
    sudo apt-get install -qq freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile-dev libfreeimage-dev libcairo2-dev libgtk2.0-dev python-lxml python-argparse libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk2.0-dev libgstreamer${GSTREAMER_VERSION}-dev libgstreamer-plugins-base${GSTREAMER_VERSION}-dev ${GSTREAMER_FFMPEG} gstreamer${GSTREAMER_VERSION}-pulseaudio gstreamer${GSTREAMER_VERSION}-x gstreamer${GSTREAMER_VERSION}-plugins-bad gstreamer${GSTREAMER_VERSION}-alsa gstreamer${GSTREAMER_VERSION}-plugins-base gstreamer${GSTREAMER_VERSION}-plugins-good || failed_message
    successed_message
}

function get_codecs {
    message "Install several gstreamer codecs (OF)"
    sudo apt-get install -qq libmpg123-dev gstreamer${GSTREAMER_VERSION}-plugins-ugly || failed_message
    successed_message
}

function get_openFrameworks {
    message "Download openFrameworks"
    wget --quiet --continue http://www.openframeworks.cc/versions/v${OF_VERSION}/${OF_FILE} -O /tmp/${OF_FILE} || failed_message
    successed_message
    mkdir ${HOME}/${OF_DIRNAME} 2>/dev/null
    if [ $? -eq 0 ]
    then
	message "Extract openFrameworks to ${HOME}/${OF_DIRNAME}"
    else
	message "Replace openFrameworks in ${HOME}/${OF_DIRNAME}" warning
    fi
    tar xfz /tmp/${OF_FILE} -C ${HOME}/${OF_DIRNAME} --strip-components=1 || failed_message
    successed_message
}

#---------- Main program ---
# Verifications
verify_prerequisites

# Compile toolchain
get_toolchain

# Install library dependencies
get_dep_libs

# Install codecs
get_codecs

# Get openFrameworks
get_openFrameworks

# Install required AddOns
get_addons

exit 1
