#pragma once
#ifndef VILAINCONSTANTS_H
#define VILAINCONSTANTS_H

#ifndef PROG_NAME
#define PROG_NAME "vilain"
#endif // PROG_NAME

namespace vilain
{
enum vilainObjectType
{
    VILAIN_OBJECT_TYPE_PLAIN_COLOR = 0,
    VILAIN_OBJECT_TYPE_2D_STILL,
    VILAIN_OBJECT_TYPE_2D_STILL_SEQUENCE,
    VILAIN_OBJECT_TYPE_MOVIE,
    VILAIN_OBJECT_TYPE_LIVE_CAMERA,
    VILAIN_OBJECT_TYPE_3D_PRIMITIVE,
    VILAIN_OBJECT_TYPE_3D_FILE,
    VILAIN_OBJECT_TYPE_3D_FILE_UV,
    VILAIN_OBJECT_TYPE_MASK = 1024     // Keep it last
};
};
#endif // VILAINCONSTANTS_H
