#ifndef VILAINCONSTANTS_H_INCLUDED
#define VILAINCONSTANTS_H_INCLUDED

#ifndef PROG_NAME
#define PROG_NAME "vilain"
#endif // PROG_NAME

enum vilainObjectType
{
    VILAIN_OBJECT_TYPE_IMAGE = 0,
    VILAIN_OBJECT_TYPE_IMAGE_SEQUENCE,
    VILAIN_OBJECT_TYPE_FLUX,
    VILAIN_OBJECT_TYPE_VIDEO,
    VILAIN_OBJECT_TYPE_SHAPE,
    VILAIN_OBJECT_TYPE_MASK = 1024     // Keep it last
};

#endif // VILAINCONSTANTS_H_INCLUDED
